# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.4
  hooks:
    # Run the linter.
    - id: ruff
      exclude: '/migrations/'
      args: [ --unsafe-fixes ]
    # Run the formatter.
    - id: ruff-format
      exclude: '/migrations/'

- repo: https://github.com/djlint/djLint
  rev: v1.35.2
  hooks:
    - id: djlint-reformat-django

    # Disabled because there are too many problems :-(
    # - id: djlint-django
    #   exclude: 'bootstrap-fiddling.html'

# Try to prevent me from pusing a pyproject.toml that says that the library is in ../library
# That doesn't work "in production", but I keep forgetting.
- repo: local
  hooks:
    - id: ensure-no-local-dependencies
      name: ensure-no-local-dependencies
      language: system
      #TODO -- only do this if PRE_COMMIT_REMOTE_BRANCH=refs/heads/main
      entry: grep --quiet "^bridge *=.*https://gitlab.com" pyproject.toml
      stages:
        - pre-push
