# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
      args: [--chars," \t"]

- repo: https://github.com/adamchainz/django-upgrade
  rev: "1.25.0"
  hooks:
    - id: django-upgrade

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.11.11
  hooks:
    # Run the linter.
    - id: ruff
      exclude: '/migrations/'
      args:
        - "--unsafe-fixes"
        - "--fix"
    # Run the formatter.
    - id: ruff-format
      exclude: '/migrations/'

- repo: https://github.com/djlint/djLint
  rev: v1.36.4
  hooks:
    - id: djlint-reformat-django

    - id: djlint-django
      exclude: 'bootstrap-fiddling.html'

# Prevent me from using a pyproject.toml that says that the library is in ../library
# That doesn't work "in production", but I keep forgetting.
- repo: local
  hooks:
    - id: ensure-no-local-dependencies
      name: ensure-no-local-dependencies
      language: script
      entry: barf-if-pyproject-points-to-relative-path.py
      stages:
        - pre-push
    - id: reformat-main-justfile
      name: reformat-main-justfile
      language: system
      entry: "just --fmt --justfile justfile"
      pass_filenames: false
      verbose: true
    - id: reformat-pg-justfile
      name: reformat-pg-justfile
      language: system
      entry: "just --unstable --fmt --justfile postgres.just"
      pass_filenames: false
      verbose: true
