volumes:
  caddy_data: {}

services:
  caddy:
    # TODO -- "Wy use the lucasloretnz caddy and not the official?"
    # i.e., either use the official image, or explain why not
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    profiles:
      - prod
