[tool.poetry]
name = "bridge_server"
version = "0.1.0"
description = "An online bridge game"
authors = ["Eric Hanchrow <eric.hanchrow@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10"

# This is a private repo, for no particularly good reason.
bridge =  { git = "git@gitlab.com:offby1/bridge.git" }
django = "^5.0.1"
pytest-django = "^4.7.0"
tqdm = "^4.66.4"
more-itertools = "^10.3.0"

[tool.poetry.group.dev.dependencies]
django-extensions = "^3.2.3"
django-debug-toolbar = "^4.4.6"
faker = "^26.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE="project.settings"
python_files = ["tests.py", "test_*.py", "*_test.py", "testing/python/*.py"]
