[tool.djlint]
use_gitignore=true
ignore="H016,H021,H023,H030,H031"

[tool.poetry]
name = "bridge_server"
version = "0.1.0"
description = "An online bridge game"
authors = ["Eric Hanchrow <eric.hanchrow@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<4.0"

django = "^5.0.1"
faker = "^26.0.0"
more-itertools = "^10.3.0"
pytest-django = "^4.7.0"
tqdm = "^4.66.4"
bridge = { git = "https://gitlab.com/offby1/bridge.git", rev = "e6d6250527fbc30537feaabc0b30c2298450bb02" }
#bridge = {path = "../library", develop = true}
django-eventstream = {extras = ["drf"], version = "^5.3.0"}
daphne = "^4.1.2"
django-template-partials = "^24.4"
whitenoise = "^6.7.0"
redis = "^5.0.8"
retrying = "^1.3.4"
sseclient = "^0.0.27"
types-requests = "^2.32.0.20240712"
platformdirs = "^4.2.2"
sentry-sdk = "^2.14.0"
docutils = "^0.21.2"
psycopg2-binary = "^2.9.9"
djangorestframework = "^3.15.2"


[tool.poetry.group.dev.dependencies]
django-extensions = "^3.2.3"
django-debug-toolbar = "^4.4.6"
ipython = "^8.26.0"
django-coverage-plugin = "^3.1.0"
django-types = "^0.19.1"
mypy = "^1.11.2"
types-tqdm = "^4.66.0.20240417"
python-lsp-server = "^1.12.0"
logging-tree = "^1.10"

[tool.pydocstyle]
# Disable pydocstyle entirely.
# This seems cleaner than uninstalling it.
# We hates it, we does.
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D106", "D212", "D213"]

[tool.coverage.run]
dynamic_context = "test_function"
plugins = [
    'django_coverage_plugin',
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE="project.dev_settings"
python_files = ["tests.py", "test_*.py", "*_test.py", "testing/python/*.py"]
