[tool.poetry]
name = "bridge_server"
version = "0.1.0"
description = "An online bridge game"
authors = ["Eric Hanchrow <eric.hanchrow@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10"

django = "^5.0.1"
faker = "^26.0.0"
more-itertools = "^10.3.0"
pytest-django = "^4.7.0"
tqdm = "^4.66.4"
bridge = {path = "../library", develop = true}
django-eventstream = {extras = ["drf"], version = "^5.3.0"}
daphne = "^4.1.2"
django-template-partials = "^24.4"
whitenoise = "^6.7.0"

[tool.poetry.group.dev.dependencies]
django-extensions = "^3.2.3"
django-debug-toolbar = "^4.4.6"
ipython = "^8.26.0"
django-coverage-plugin = "^3.1.0"

[tool.coverage.run]
dynamic_context = "test_function"
plugins = [
    'django_coverage_plugin',
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE="project.settings"
python_files = ["tests.py", "test_*.py", "*_test.py", "testing/python/*.py"]
