{
 "title": "Reasonable-looking dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_procs_running", "legendFormat": "{{__name__}}" },
    { "expr": "node_procs_blocked", "legendFormat": "{{__name__}}" },
    { "expr": "process_open_fds", "legendFormat": "{{__name__}}" },
    { "expr": "node_load1", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Database Inserts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"bridge\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"bridge\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "request latencies",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(django_http_requests_latency_including_middlewares_seconds_bucket{}[$__rate_interval]) ))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(django_http_requests_latency_including_middlewares_seconds_bucket{}[$__rate_interval]) ))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(django_http_requests_latency_including_middlewares_seconds_bucket{}[$__rate_interval]) ))",
     "legendFormat": "50th Percentile"
    }
   ]
  }
 ]
}