{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Model Inserts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(django_model_inserts_total[$__rate_interval])",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "Postgres Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"bridge\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "request latencies",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(django_http_requests_latency_including_middlewares_seconds_bucket{}[$__rate_interval]) ))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(django_http_requests_latency_including_middlewares_seconds_bucket{}[$__rate_interval]) ))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(django_http_requests_latency_including_middlewares_seconds_bucket{}[$__rate_interval]) ))",
     "legendFormat": "50th Percentile"
    }
   ]
  }
 ]
}