# Generated by Django 5.0.7 on 2024-08-01 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('east', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_east', to='app.player')),
                ('north', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_north', to='app.player')),
                ('south', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_south', to='app.player')),
                ('west', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_west', to='app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West')], max_length=1)),
                ('serialized', models.CharField(db_comment='A short string with which we can create a bridge.contract.Call object', max_length=10)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.table')),
            ],
        ),
    ]
