# Generated by Django 5.0.7 on 2024-07-31 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='table',
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('N', 'North'), ('E', 'East'), ('S', 'South'), ('W', 'West')], max_length=1)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.table')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='seat',
            field=models.OneToOneField(blank=True, db_comment="If NULL, then I'm in the lobby", null=True, on_delete=django.db.models.deletion.CASCADE, to='app.seat'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('table', 'direction'), name='composite_primary_key'),
        ),
    ]
