# Generated by Django 5.0.7 on 2024-08-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='looking_for_partner',
            field=models.BooleanField(default=False),
        ),
    ]
