# Generated by Django 5.0.7 on 2024-08-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_player_looking_for_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['user__username']},
        ),
    ]
