# Generated by Django 5.0.7 on 2024-07-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_player_name_player_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='club',
        ),
        migrations.RemoveConstraint(
            model_name='table',
            name='composite_primary_key',
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
