# Generated by Django 5.1 on 2024-08-12 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_seat_app_seat_direction_valid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.player'),
        ),
        migrations.DeleteModel(
            name='Call',
        ),
    ]
