# Generated by Django 5.0.7 on 2024-07-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_player_table_seat_player_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='cards',
            field=models.CharField(blank=True, db_comment='String of even length; each pair of characters is like ♧2', default='', max_length=26),
        ),
    ]
