# Generated by Django 5.0.7 on 2024-08-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seat_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='cards',
            field=models.JSONField(blank=True, db_comment='List of pairs of characters, each like `♧2`.', default=list),
        ),
    ]
