# Generated by Django 5.1 on 2024-08-16 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_playermessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermessage',
            name='from_player',
        ),
        migrations.RemoveField(
            model_name='playermessage',
            name='recipient',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=128)),
                ('from_player', models.ForeignKey(db_comment="NULL means it came from 'the system'", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_message', to='app.player')),
                ('player_recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.player')),
                ('table_recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.table')),
            ],
        ),
        migrations.DeleteModel(
            name='LobbyMessage',
        ),
        migrations.DeleteModel(
            name='PlayerMessage',
        ),
    ]
