# Generated by Django 5.1 on 2024-08-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lobby_remove_message_player_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seat',
            name='no_more_than_one_player_per_table',
        ),
        migrations.RemoveConstraint(
            model_name='seat',
            name='no_more_than_four_directions_per_table',
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('player',), name='app_seat_no_more_than_one_seat_per_player'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('direction', 'table'), name='app_seat_no_more_than_four_directions_per_table'),
        ),
    ]
