# Generated by Django 5.1 on 2024-08-22 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_seat_no_more_than_one_player_per_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'ordering': ['direction']},
        ),
    ]
