# Generated by Django 5.1 on 2024-08-26 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_player_app_player_cant_be_own_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns_vulnerable', models.BooleanField()),
                ('ew_vulnerable', models.BooleanField()),
                ('dealer', models.SmallIntegerField()),
                ('cards', models.CharField(max_length=104)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.table')),
            ],
        ),
    ]
