# Generated by Django 5.1 on 2024-08-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_board_cards_board_east_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seat')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serialized', models.CharField(db_comment='A short string with which we can create a bridge.contract.Call object', max_length=10)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.handrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('serialized', models.CharField(db_comment='A short string with which we can create a bridge.card.Card object', max_length=2)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.handrecord')),
            ],
        ),
    ]
