# Generated by Django 5.1 on 2024-08-27 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_handrecord_call_play'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='handrecord',
            name='seat',
        ),
        migrations.AddField(
            model_name='handrecord',
            name='table',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.table'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='dealer',
            field=models.SmallIntegerField(db_comment='corresponds to bridge library\'s "direction" '),
        ),
    ]
