# Generated by Django 5.1 on 2024-08-28 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_handrecord_seat_handrecord_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='table',
        ),
        migrations.AddField(
            model_name='handrecord',
            name='board',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.board'),
            preserve_default=False,
        ),
    ]
