# Generated by Django 5.1 on 2024-09-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_usermitplaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_human',
            field=models.BooleanField(default=False),
        ),
    ]
