# Generated by Django 5.1 on 2024-09-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_seat_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='won_its_trick',
            field=models.BooleanField(null=True),
        ),
    ]
