# Generated by Django 5.1 on 2024-09-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_play_won_its_trick'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HandRecord',
            new_name='HandAction',
        ),
    ]
