# Generated by Django 5.1 on 2024-09-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_handaction_hand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_human',
        ),
        migrations.AddField(
            model_name='player',
            name='allow_bot_to_play_for_me',
            field=models.BooleanField(default=True),
        ),
    ]
