# Generated by Django 5.1 on 2024-10-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_hand_board_alter_seat_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='open_access',
            field=models.BooleanField(db_comment='For debugging only! Only settable via the admin site', default=False),
        ),
    ]
