# Generated by Django 5.1 on 2024-10-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_hand_open_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='open_access',
            field=models.BooleanField(db_comment='For debugging only! Settable via the admin site, and maaaaybe by a special "god-mode" switch in the UI', default=False),
        ),
    ]
