# Generated by Django 5.1 on 2024-10-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_hand_open_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='won_its_trick',
        ),
    ]
