# Generated by Django 5.1 on 2024-10-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_play_won_its_trick'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seat',
            name='app_seat_direction_valid',
        ),
        migrations.AlterField(
            model_name='seat',
            name='direction',
            field=models.SmallIntegerField(choices=[(1, 'North'), (2, 'East'), (3, 'South'), (4, 'West')]),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', {1: 'North', 2: 'East', 3: 'South', 4: 'West'})), name='app_seat_direction_valid'),
        ),
    ]
