# Generated by Django 5.1 on 2024-10-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_remove_seat_app_seat_direction_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='tempo_seconds',
            field=models.FloatField(db_comment='Time, in seconds, that the bot will wait before making a call or play', default=1.0),
        ),
    ]
