# Generated by Django 5.1.2 on 2024-11-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_table_tempo_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='number',
            field=models.SmallIntegerField(default=0),
        ),
    ]
