# Generated by Django 5.1.2 on 2024-11-06 15:11

from django.db import migrations


def backfill_board_numbers(apps, schema_editor):
    Board = apps.get_model("app", "Board")

    for index, board in enumerate(Board.objects.order_by("id").all()):
        board.number = index + 1
        board.save(update_fields=["number"])


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0030_board_number"),
    ]

    operations = [
        migrations.RunPython(backfill_board_numbers, reverse_code=migrations.RunPython.noop),
    ]
