# Generated by Django 5.1.2 on 2024-11-17 22:23

from app.models.board import BOARDS_PER_TOURNAMENT
from django.db import migrations


def backfill_tournaments(apps, schema_editor) -> None:
    Board = apps.get_model("app", "Board")
    Tournament = apps.get_model("app", "Tournament")

    for index, board in enumerate(Board.objects.order_by("id").all()):
        desired_tournement_pk = index // BOARDS_PER_TOURNAMENT
        t, _ = Tournament.objects.get_or_create(pk=desired_tournement_pk)
        board.tournament = t
        board.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0033_tournament_remove_board_number_board_tournament"),
    ]

    operations = [
        migrations.operations.RunPython(code=backfill_tournaments),
    ]
