# Generated by Django 5.1.2 on 2024-11-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_tournament_board_tournament'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('number', 'tournament'), name='app_board_combination_of_board_number_and_tournament_number'),
        ),
    ]
