# Generated by Django 5.1.2 on 2024-11-18 19:52

from django.db import migrations


def backfill_currently_seated(apps, schema_editor):
    Player = apps.get_model("app", "Player")
    Seat = apps.get_model("app", "Seat")

    for player in Player.objects.all():
        player.currently_seated = Seat.objects.filter(player=player).exists()
        player.save(update_fields=["currently_seated"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_player_currently_seated'),
    ]

    operations = [
        migrations.RunPython(backfill_currently_seated, reverse_code=migrations.RunPython.noop),
    ]
