# Generated by Django 5.1.2 on 2024-11-17 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_board_app_board_combination_of_board_number_and_tournament_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tournament'),
        ),
    ]
