# Generated by Django 5.1.2 on 2024-11-17 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_backfill_tournaments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tournament'),
        ),
    ]
