# Generated by Django 5.1.2 on 2024-11-19 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20241118_1952'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seat',
            name='app_seat_no_more_than_one_seat_per_player',
        ),
    ]
