# Generated by Django 5.1.2 on 2024-11-19 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_board_tournament'),
        ('app', '0035_remove_seat_app_seat_no_more_than_one_seat_per_player'),
    ]

    operations = [
    ]
