# Generated by Django 5.1.4 on 2024-12-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_merge_20241119_0336"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="tempo_seconds",
            field=models.FloatField(
                db_comment="Time, in seconds, that the bot will wait before making a call or play",
                default=10.0,
            ),
        ),
    ]
