# Generated by Django 5.1.4 on 2025-01-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_alter_table_tempo_seconds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="tempo_seconds",
            field=models.FloatField(
                db_comment="Time, in seconds, that the bot will wait before making a call or play",
                default=1.0,
            ),
        ),
    ]
