# Generated by Django 5.1.4 on 2025-01-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_alter_table_tempo_seconds"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="allow_bot_to_play_for_me",
        ),
        migrations.CreateModel(
            name="BotPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.player"
                    ),
                ),
            ],
            options={
                "db_table_comment": "Those players whose PKs appear here will have a bot play for them.",
            },
        ),
    ]
