# Generated by Django 5.1.4 on 2025-01-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_remove_player_allow_bot_to_play_for_me_botplayer"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="dealer_letter",
            field=models.CharField(
                db_comment='corresponds to bridge library\'s "direction" ', default="?"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seat",
            name="direction_letter",
            field=models.CharField(
                choices=[("N", "NORTH"), ("E", "EAST"), ("S", "SOUTH"), ("W", "WEST")],
                default="?",
            ),
            preserve_default=False,
        ),
    ]
