# Generated by Django 5.1.4 on 2025-01-13 19:41

from django.db import migrations


def populate_direction_letters(apps, schema_editor):
    Seat = apps.get_model("app", "Seat")
    for seat in Seat.objects.all():
        seat.direction_letter = "NESW"[seat.direction - 1]
        seat.save()

    Board = apps.get_model("app", "Board")
    for board in Board.objects.all():
        board.dealer_letter = "NESW"[board.dealer - 1]
        board.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_board_dealer_letter_seat_direction_letter"),
    ]

    operations = [
        migrations.RunPython(populate_direction_letters, reverse_code=migrations.RunPython.noop),
    ]
