# Generated by Django 5.1.4 on 2025-01-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_auto_20250113_1941"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(("dealer_letter__in", "NESW")),
                name="app_board_dealer_must_be_compass_letter",
            ),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "direction_letter__in",
                        {"E": "EAST", "N": "NORTH", "S": "SOUTH", "W": "WEST"},
                    )
                ),
                name="app_seat_direction_letter_valid",
            ),
        ),
    ]
