# Generated by Django 5.1.4 on 2025-01-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0042_board_app_board_dealer_must_be_compass_letter_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="board",
            name="app_board_dealer_must_be_compass_letter",
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(("dealer_letter__in", "NESW")),
                name="app_board_dealer_letter_must_be_compass_letter",
            ),
        ),
    ]
