# Generated by Django 5.1.4 on 2025-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_alter_seat_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hand",
            constraint=models.UniqueConstraint(
                fields=("board", "table"),
                name="app_hand_a_board_can_be_played_only_once_at_a_given_table",
            ),
        ),
    ]
