# Generated by Django 5.1.4 on 2025-01-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_hand_app_hand_a_board_can_be_played_only_once_at_a_given_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="boards_played",
            field=models.ManyToManyField(to="app.board"),
        ),
    ]
