# Generated by Django 5.1.4 on 2025-01-19 00:05

from django.db import migrations


def backfill_played_boards(apps, schema_editor):
    Hand = apps.get_model("app", "Hand")

    for h in Hand.objects.all():
        for seat in h.table.seat_set.all():
            seat.player.boards_played.add(h.board)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_player_boards_played"),
    ]

    operations = [
        migrations.RunPython(backfill_played_boards, reverse_code=migrations.RunPython.noop),
    ]
