# Generated by Django 5.1.4 on 2025-01-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_player_boards_played"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="boards_played",
            new_name="boards_played_v2",
        ),
    ]
