# Generated by Django 5.1.4 on 2025-01-19 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_alter_botplayer_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botplayer",
            name="player",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="app.player"
            ),
        ),
    ]
