# Generated by Django 5.1.4 on 2025-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_alter_botplayer_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="display_number",
            field=models.SmallIntegerField(null=True),
        ),
    ]
