# Generated by Django 5.1.4 on 2025-01-19 17:09

from django.db import migrations


def backfill_board_display_number(apps, schema_editor):
    Board = apps.get_model("app", "Board")

    for b in Board.objects.all():
        b.display_number = 1 + (b.pk % 16)
        b.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_board_display_number"),
    ]

    operations = [
        migrations.RunPython(backfill_board_display_number, reverse_code=migrations.RunPython.noop),
    ]
