# Generated by Django 5.1.4 on 2025-01-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0051_auto_20250119_1709"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="display_number",
            field=models.SmallIntegerField(),
        ),
    ]
