# Generated by Django 5.1.4 on 2025-01-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0052_alter_board_display_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
