# Generated by Django 5.1.4 on 2025-01-23 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0053_tournament_is_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="tournament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.tournament",
            ),
        ),
    ]
