# Generated by Django 5.1.4 on 2025-01-23 22:37

from django.db import migrations


def backfill_table_tournaments(apps, schema_editor):
    Board = apps.get_model("app", "Board")
    Hand = apps.get_model("app", "Hand")
    Table = apps.get_model("app", "Table")
    Tournament = apps.get_model("app", "Tournament")

    for t in Table.objects.all():
        if t.tournament is None:
            hands = Hand.objects.filter(table=t)
            boards = Board.objects.filter(hand__in=hands)
            tournaments = boards.values_list("tournament", flat=True).distinct()
            assert len(tournaments) == 1, f"Hmm, {t=} hasn't exactly one tournament: {tournaments=}"
            t.tournament = Tournament.objects.get(pk=tournaments[0])
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_table_tournament"),
    ]

    operations = [
        migrations.RunPython(backfill_table_tournaments, reverse_code=migrations.RunPython.noop),
    ]
