# Generated by Django 5.1.4 on 2025-01-23 22:37

from django.db import migrations


def backfill_table_tournaments(apps, schema_editor):
    Table = apps.get_model("app", "Table")
    Tournament = apps.get_model("app", "Tournament")

    for t in Table.objects.all():
        if t.tournament is None:
            t.tournament = Tournament.objects.maybe_new_tournament()
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0054_table_tournament"),
    ]

    operations = []
