# Generated by Django 5.1.4 on 2025-01-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_alter_table_tournament"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="player",
            field=models.ForeignKey(
                db_comment="this is None *only* if this player has *never* been seated.  Use `Player.currently_seated` for most things.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historical_seat_set",
                to="app.player",
            ),
        ),
    ]
