# Generated by Django 5.1.4 on 2025-01-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_alter_seat_player"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="synthetic",
            field=models.BooleanField(default=False),
        ),
    ]
