# Generated by Django 5.1.4 on 2025-02-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0058_player_synthetic"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="allow_bot_to_play_for_me",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="BotPlayer",
        ),
    ]
