# Generated by Django 5.1.4 on 2025-02-01 17:15

from django.db import migrations


def backfill_allow_bot_to_play_for_me(apps, schema_editor):
    Player = apps.get_model("app", "Player")
    for synth in Player.objects.filter(synthetic=True).filter(allow_bot_to_play_for_me=False):
        synth.allow_bot_to_play_for_me = True
        synth.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0059_player_allow_bot_to_play_for_me_delete_botplayer"),
    ]

    operations = [
        migrations.RunPython(backfill_allow_bot_to_play_for_me, reverse_code=migrations.RunPython.noop),
    ]
