# Generated by Django 5.1.4 on 2025-02-01 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0060_auto_20250201_1715"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="player",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("synthetic", False),
                    ("allow_bot_to_play_for_me", True),
                    _connector="OR",
                ),
                name="synthetic_players_must_allow_bot_to_play_for_them",
            ),
        ),
    ]
