# Generated by Django 5.1.4 on 2025-02-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0061_player_synthetic_players_must_allow_bot_to_play_for_them"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="display_number",
            field=models.SmallIntegerField(null=True),
        ),
    ]
