# Generated by Django 5.1.4 on 2025-02-05 03:28

from django.db import migrations


def backfill_tournament_display_number(apps, schema_editor):
    Tournament = apps.get_model("app", "Tournament")
    max_display_number = 0
    for t in Tournament.objects.all():
        if t.display_number is None:
            t.display_number = max_display_number + 1
            t.save()
        max_display_number = max(max_display_number, t.display_number)


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0062_tournament_display_number"),
    ]

    operations = [
        migrations.RunPython(backfill_tournament_display_number, reverse_code=migrations.RunPython.noop),
    ]
