# Generated by Django 5.1.4 on 2025-02-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0063_auto_20250205_0328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="display_number",
            field=models.SmallIntegerField(unique=True),
        ),
    ]
