# Generated by Django 5.1.4 on 2025-02-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_alter_tournament_display_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="abandoned_because",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="play_completion_deadline",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="signup_deadline",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("signup_deadline__isnull", True),
                        ("play_completion_deadline__isnull", True),
                    ),
                    models.Q(
                        ("signup_deadline__isnull", False),
                        ("play_completion_deadline__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="app_tournament_cant_have_just_one_deadline",
            ),
        ),
    ]
