# Generated by Django 5.1.4 on 2025-02-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0064_alter_tournament_display_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="play_completion_deadline",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="tournament",
            name="signup_deadline",
            field=models.DateTimeField(default=None),
        ),
    ]
