# Generated by Django 5.1.4 on 2025-02-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_tournament_play_completion_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="play_completion_deadline",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="signup_deadline",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
