# Generated by Django 5.1.4 on 2025-02-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0065_hand_abandoned_because_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("signup_deadline__isnull", True),
                        ("play_completion_deadline__isnull", True),
                    ),
                    ("play_completion_deadline__gt", models.F("signup_deadline")),
                    _connector="OR",
                ),
                name="app_tournament_play_deadline_must_follow_signup_deadline",
            ),
        ),
    ]
