# Generated by Django 5.1.4 on 2025-02-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0066_alter_tournament_play_completion_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="abandoned_because",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
