# Generated by Django 5.1.4 on 2025-02-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0066_tournament_app_tournament_play_deadline_must_follow_signup_deadline",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="play_completion_deadline",
            field=models.DateTimeField(
                db_comment="NULL means 'infintely far in the future'",
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="signup_deadline",
            field=models.DateTimeField(
                db_comment="NULL means 'infintely far in the future'",
                default=None,
                null=True,
            ),
        ),
    ]
