# Generated by Django 5.1.4 on 2025-02-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0067_alter_tournament_play_completion_deadline_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                fields=("display_number", "tournament_id"),
                name="app_board_display_number_unique_per_tournament",
            ),
        ),
    ]
