# Generated by Django 5.1.4 on 2025-02-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0071_rename_tournamentsignups_tournamentsignup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="play_completion_deadline",
            field=models.DateTimeField(
                blank=True,
                db_comment="NULL means 'infintely far in the future'",
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="signup_deadline",
            field=models.DateTimeField(
                blank=True,
                db_comment="NULL means 'infintely far in the future'",
                default=None,
                null=True,
            ),
        ),
    ]
