# Generated by Django 5.1.6 on 2025-02-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_alter_call_options_call_created_call_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="display_number",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("display_number", "tournament_id"),
                name="app_table_display_number_unique_per_tournament",
            ),
        ),
    ]
