# Generated by Django 5.1.6 on 2025-03-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_alter_call_options_call_created_call_modified_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("direction", "table"),
                name="app_seat_no_more_than_four_directions_per_table",
            ),
        ),
    ]
