# Generated by Django 5.1.6 on 2025-03-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0073_alter_call_options_call_created_call_modified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="table",
            name="display_number",
            field=models.SmallIntegerField(null=True),
        ),
    ]
