# Generated by Django 5.1.6 on 2025-03-02 14:57

from django.db import migrations, models


def backfill_table_display_number(apps, schema_editor):
    Table = apps.get_model("app", "Table")

    for t in Table.objects.order_by("tournament_id", "id").all():
        if t.display_number is None:
            max_ = Table.objects.aggregate(models.Max("display_number"))["display_number__max"] or 0
            t.display_number = max_ + 1
            t.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_table_display_number"),
    ]

    operations = [
        migrations.RunPython(backfill_table_display_number, reverse_code=migrations.RunPython.noop),
    ]
