# Generated by Django 5.1.6 on 2025-03-23 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_seat_app_seat_no_more_than_four_directions_per_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="currently_seated",
        ),
        migrations.AddField(
            model_name="player",
            name="current_seat",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="I_dunno",
                to="app.seat",
            ),
        ),
    ]
