# Generated by Django 5.2 on 2025-04-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_seat_app_seat_no_more_than_four_directions_per_table_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.UniqueConstraint(
                fields=("display_number",), name="app_tournament_display_number_unique"
            ),
        ),
    ]
