# Generated by Django 5.1.6 on 2025-03-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_seat_app_seat_no_more_than_four_directions_per_table_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hand",
            name="app_hand_a_board_can_be_played_only_once_at_a_given_table",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="player",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="table",
        ),
        migrations.RemoveField(
            model_name="table",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="hand",
            name="table",
        ),
        migrations.AddField(
            model_name="hand",
            name="east",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="east",
                to="app.player",
            ),
        ),
        migrations.AddField(
            model_name="hand",
            name="north",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="north",
                to="app.player",
            ),
        ),
        migrations.AddField(
            model_name="hand",
            name="south",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="south",
                to="app.player",
            ),
        ),
        migrations.AddField(
            model_name="hand",
            name="table_display_number",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="hand",
            name="west",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="west",
                to="app.player",
            ),
        ),
        migrations.AlterField(
            model_name="hand",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="hand",
            constraint=models.UniqueConstraint(
                fields=("board", "north", "east", "south", "west"),
                name="app_hand_a_board_can_be_played_only_once_by_four_players",
            ),
        ),
        migrations.DeleteModel(
            name="Seat",
        ),
        migrations.DeleteModel(
            name="Table",
        ),
    ]
