# Generated by Django 5.1.6 on 2025-03-29 16:34

from django.db import migrations


def backfill_new_hand_attributes(apps, schema_editor):
    Hand = apps.get_model("app", "Hand")

    for h in Hand.objects.all():
        table = h.table

        for seat in table.seat_set.all():
            attribute = {"N": "North", "E": "East", "S": "South", "W": "West"}[seat.direction]
            setattr(h, f"{attribute}_id", seat.player_id)

        h.table_display_number = table.id

        h.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_add_new_hand_attributes"),
    ]

    operations = [
        migrations.RunPython(backfill_new_hand_attributes, reverse_code=migrations.RunPython.noop),
    ]
