# Generated by Django 5.1.6 on 2025-03-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_auto_20250302_1457"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="display_number",
            field=models.SmallIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="table",
            constraint=models.UniqueConstraint(
                fields=("display_number", "tournament_id"),
                name="app_table_display_number_unique_per_tournament",
            ),
        ),
    ]
