# Generated by Django 5.1.6 on 2025-03-23 16:30

from django.db import migrations


def backfill_current_seat(apps, schema_editor):
    Player = apps.get_model("app", "Player")
    Seat = apps.get_model("app", "Seat")

    for p in Player.objects.all():
        cs = Seat.objects.filter(player=p).order_by("-id").first()
        if cs is not None:
            p.current_seat = cs
        else:
            p.cs = None
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_remove_player_currently_seated_player_current_seat"),
    ]

    operations = [
        migrations.RunPython(backfill_current_seat, reverse_code=migrations.RunPython.noop),
    ]
