# Generated by Django 5.1.6 on 2025-03-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0075_remove_seat_player_remove_seat_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="boards_played",
        ),
    ]
