# Generated by Django 5.1.6 on 2025-03-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_remove_player_boards_played"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hand",
            old_name="east",
            new_name="East",
        ),
        migrations.RenameField(
            model_name="hand",
            old_name="north",
            new_name="North",
        ),
        migrations.RenameField(
            model_name="hand",
            old_name="south",
            new_name="South",
        ),
        migrations.RenameField(
            model_name="hand",
            old_name="west",
            new_name="West",
        ),
    ]
