# Generated by Django 5.1.6 on 2025-03-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_backfill_new_hand_attributes"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hand",
            name="app_hand_a_board_can_be_played_only_once_at_a_given_table",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="player",
        ),
        migrations.RemoveField(
            model_name="seat",
            name="table",
        ),
        migrations.RemoveField(
            model_name="table",
            name="tournament",
        ),
        migrations.RemoveField(
            model_name="hand",
            name="table",
        ),
        migrations.RemoveField(
            model_name="player",
            name="boards_played",
        ),
        migrations.RemoveField(
            model_name="player",
            name="currently_seated",
        ),
        migrations.AlterField(
            model_name="hand",
            name="abandoned_because",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="hand",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="hand",
            constraint=models.UniqueConstraint(
                fields=("board", "North", "East", "South", "West"),
                name="app_hand_a_board_can_be_played_only_once_by_four_players",
            ),
        ),
        migrations.DeleteModel(
            name="Seat",
        ),
        migrations.DeleteModel(
            name="Table",
        ),
    ]
