# Generated by Django 5.1.6 on 2025-03-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0076_alter_table_display_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="group",
            field=models.CharField(
                db_comment=" A, B, C &c, NULL means not yet assigned ",
                max_length=1,
                null=True,
            ),
        ),
    ]
