# Generated by Django 5.1.6 on 2025-03-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0077_board_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="boards_per_round_per_table",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
