# Generated by Django 5.1.6 on 2025-03-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0077_rename_east_hand_east_rename_north_hand_north_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hand",
            name="app_hand_a_board_can_be_played_only_once_by_four_players",
        ),
        migrations.AddConstraint(
            model_name="hand",
            constraint=models.UniqueConstraint(
                fields=("board", "North", "East", "South", "West"),
                name="app_hand_a_board_can_be_played_only_once_by_four_players",
            ),
        ),
    ]
