# Generated by Django 5.1.6 on 2025-03-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0077_remove_seat_player_remove_seat_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="group",
            field=models.CharField(
                db_comment=" A, B, C &c, NULL means not yet assigned ",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tournament",
            name="boards_per_round_per_table",
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
