# Generated by Django 5.1.6 on 2025-03-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0078_tournament_boards_per_round_per_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="table",
            name="app_table_display_number_unique_per_tournament",
        ),
    ]
