# Generated by Django 5.1.6 on 2025-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0078_tournament_boards_per_round_per_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hand",
            name="abandoned_because",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
