# Generated by Django 5.1.7 on 2025-04-04 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0078_board_group_tournament_boards_per_round_per_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tournament",
            name="app_tournament_cant_have_just_one_deadline",
        ),
        migrations.RemoveConstraint(
            model_name="tournament",
            name="app_tournament_play_deadline_must_follow_signup_deadline",
        ),
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("play_completion_deadline__isnull", True),
                    ("play_completion_deadline__gt", models.F("signup_deadline")),
                    _connector="OR",
                ),
                name="app_tournament_play_deadline_must_follow_signup_deadline",
            ),
        ),
    ]
