# Generated by Django 5.1.6 on 2025-03-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0078_remove_hand_app_hand_a_board_can_be_played_only_once_by_four_players_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="currently_seated",
        ),
    ]
