# Generated by Django 5.1.6 on 2025-03-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0079_remove_player_currently_seated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hand",
            name="abandoned_because",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
