# Generated by Django 5.1.7 on 2025-04-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0079_remove_tournament_app_tournament_cant_have_just_one_deadline_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hand",
            options={
                "ordering": [
                    "board__tournament__display_number",
                    "table_display_number",
                    "board__display_number",
                ]
            },
        ),
    ]
