# Generated by Django 5.1.6 on 2025-03-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0074_seat_app_seat_no_more_than_four_directions_per_table_and_more"),
        ("app", "0079_alter_hand_abandoned_because"),
    ]

    operations = []
