# Generated by Django 5.1.6 on 2025-03-25 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0080_merge_20250320_1448"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="player",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historical_seat_set",
                to="app.player",
            ),
        ),
    ]
