# Generated by Django 5.2 on 2025-04-10 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0080_alter_hand_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hand",
            name="East",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="east",
                to="app.player",
            ),
        ),
        migrations.AlterField(
            model_name="hand",
            name="North",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="north",
                to="app.player",
            ),
        ),
        migrations.AlterField(
            model_name="hand",
            name="South",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="south",
                to="app.player",
            ),
        ),
        migrations.AlterField(
            model_name="hand",
            name="West",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="west",
                to="app.player",
            ),
        ),
        migrations.AlterField(
            model_name="hand",
            name="table_display_number",
            field=models.SmallIntegerField(),
        ),
    ]
