# Generated by Django 5.2 on 2025-04-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0081_alter_hand_east_alter_hand_north_alter_hand_south_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tournament",
            constraint=models.UniqueConstraint(
                fields=("display_number",), name="app_tournament_display_number_unique"
            ),
        ),
    ]
