# Generated by Django 5.2 on 2025-04-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0082_tournament_app_tournament_display_number_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hand",
            constraint=models.UniqueConstraint(
                fields=("board", "table_display_number"),
                name="app_hand_a_board_can_be_played_only_once_at_a_given_table",
            ),
        ),
    ]
