# Generated by Django 5.2 on 2025-05-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0084_auto_20250501_2048"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="play_completion_deadline",
            field=models.DateTimeField(
                blank=True,
                db_comment="NULL means 'infintely far in the future'",
                default=None,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="signup_deadline",
            field=models.DateTimeField(
                blank=True,
                db_comment="NULL means 'infintely far in the future'",
                default=None,
            ),
        ),
    ]
