# Generated by Django 5.2 on 2025-05-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0085_alter_tournament_play_completion_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="play_completion_deadline",
            field=models.DateTimeField(
                blank=True,
                db_comment="NULL means we don't yet know how many players we have, hence cannot compute a movement",
                default=None,
                null=True,
            ),
        ),
    ]
