# Generated by Django 5.2.1 on 2025-05-23 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0086_alter_tournament_play_completion_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="play_completion_deadline",
            field=models.DateTimeField(
                db_comment='"a billion years from now" means we don\'t yet know how many players we have, hence cannot compute a movement',
                default=datetime.datetime(
                    9999, 12, 31, 23, 59, 59, 999999, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="signup_deadline",
            field=models.DateTimeField(),
        ),
    ]
