# Generated by Django 5.2.1 on 2025-06-02 03:06

from django.db import migrations


def nuke_boards_with_null_groups(apps, schema_editor):
    Board = apps.get_model("app", "Board")
    for b in Board.objects.all():
        if b.group is None:
            b.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0087_alter_tournament_play_completion_deadline_and_more"),
    ]

    operations = [
        migrations.RunPython(nuke_boards_with_null_groups, reverse_code=migrations.RunPython.noop),
    ]
