# Generated by Django 5.2.1 on 2025-06-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0088_auto_20250602_0306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="group",
            field=models.CharField(db_comment=" A, B, C &c ", max_length=1),
        ),
    ]
