# Generated by Django 5.2.1 on 2025-06-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0089_alter_board_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="tempo_seconds",
            field=models.FloatField(
                db_comment="Time, in seconds, that the bot will wait before making a call or play",
                default=1.0,
            ),
        ),
    ]
