# Generated by Django 5.2.1 on 2025-06-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0090_tournament_tempo_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
