# Generated by Django 5.2.1 on 2025-06-23 18:26

from django.db import migrations


def old_is_complete(hand):
    if hand.play_set.count() == 52:
        return True

    if hand.call_set.count() == 4 and hand.call_set.filter(serialized="Pass").count() == 4:
        return True

    return False


def backfill_is_complete(apps, schema_editor):
    Hand = apps.get_model("app", "Hand")
    for h in Hand.objects.all():
        if old_is_complete(h):
            h.is_complete = True
            h.save()

class Migration(migrations.Migration):

    dependencies = [
        ("app", "0091_hand_is_complete"),
    ]

    operations = [
        migrations.RunPython(backfill_is_complete, reverse_code=migrations.RunPython.noop),
    ]
