# Generated by Django 5.2.1 on 2025-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0092_auto_20250623_1826"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="is_complete",
        ),
        migrations.AddField(
            model_name="tournament",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
