# Generated by Django 5.2.1 on 2025-07-04 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0093_remove_tournament_is_complete_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="current_direction_letter",
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="current_hand",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.hand"
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("current_hand__isnull", False),
                        ("current_direction_letter__isnull", False),
                    ),
                    models.Q(
                        ("current_hand__isnull", True),
                        ("current_direction_letter__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="current_hand_and_direction_gotta_either_be_both_null_or_else_neither",
            ),
        ),
    ]
