# Generated by Django 5.2.1 on 2025-07-05 17:23

from django.db import migrations, models

from app.models.common import attribute_names

def old_current_hand(apps, player):
    Hand = apps.get_model("app", "Hand")

    expression = models.Q(pk__in=[])
    for direction in attribute_names:
        expression |= models.Q(**{direction: player})

    hands_played = Hand.objects.filter(expression)

    for h in hands_played.filter(
        is_complete=False, abandoned_because__isnull=True
    ):
        for direction_name in attribute_names:
            if getattr(h, direction_name) == player:
                return h

    return None



def backfill_current_hand(apps, schema_editor):
    Player = apps.get_model("app", "Player")
    for p in Player.objects.all():
        ch = old_current_hand(apps, p)
        if ch:
            p.current_hand = ch
            p.save()

class Migration(migrations.Migration):

    dependencies = [
        ("app", "0094_player_current_hand"),
    ]

    operations = [migrations.RunPython(backfill_current_hand, reverse_code=migrations.RunPython.noop),]
