# Generated by Django 5.2.1 on 2025-07-04 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0094_player_current_direction_letter_player_current_hand_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="player",
            name="current_hand_and_direction_gotta_either_be_both_null_or_else_neither",
        ),
        migrations.RemoveField(
            model_name="player",
            name="current_direction_letter",
        ),
    ]
