# Generated by Django 5.2.1 on 2025-07-07 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0095_auto_20250705_1723"),
    ]

    operations = [
        migrations.AddField(
            model_name="hand",
            name="last_action_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
