# Generated by Django 5.2.1 on 2025-07-24 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0096_hand_last_action_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="random_state",
            field=models.BinaryField(null=True),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("current_hand__isnull", True),
                    ("random_state__isnull", False),
                    _negated=True,
                ),
                name="random_state_is_set_only_when_seated",
            ),
        ),
    ]
