# Generated by Django 5.2.4 on 2025-08-01 22:56

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0097_player_random_state_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="last_action",
            field=models.JSONField(
                db_comment="Tuple: [timestamp, str].  The string values can be 'joined', 'logged in', 'called', 'played'",
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
