# Generated by Django 5.2.4 on 2025-08-01 23:19

import datetime

from django.db import migrations
from django.db import models
from django.db.models import Q
from app.models.common import attribute_names


def has_player_Q(player):
    expression = Q(pk__in=[])
    for direction in attribute_names:
        expression |= Q(**{direction: player})

    return expression


def last_action(h) -> tuple[datetime.datetime, str]:
    rv = (h.created, "joined hand")

    if (most_recent_call := h.call_set.order_by("-created").first()) is not None:
        if most_recent_call.created > rv[0]:  # it better be, but you never know
            rv = (most_recent_call.created, "called")

    if (most_recent_play := h.play_set.order_by("-created").first()) is not None:
        if most_recent_play.created > rv[0]:
            rv = (most_recent_play.created, "played")

    return rv


def backfill_last_activity(apps, schema_editor):
    Hand  = apps.get_model("app", "Hand")
    Player = apps.get_model("app", "Player")
    amended_attr_names = [f"current_hand__{a}" for a in attribute_names]

    for p in Player.objects.select_related("current_hand", *amended_attr_names).filter(last_action__isnull=True):
        rv = (p.created, "joined")
        if p.user.last_login and p.user.last_login > rv[0]:
            rv = (p.user.last_login, "logged in")

        if (h := Hand.objects.filter(has_player_Q(p)).first()) is not None:
            # TODO: somehow narrow stuff down to the most recent action that *we* took in this hand, as opposed to my
            # partner or opponents
            hand_last_action = last_action(h)
            if hand_last_action[0] > rv[0]:
                rv = hand_last_action
        p.last_action = rv
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0098_player_last_action"),
    ]

    operations = [migrations.RunPython(backfill_last_activity, reverse_code=migrations.RunPython.noop)]
