# Generated by Django 5.2.6 on 2025-09-22 19:07

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0099_auto_20250801_2319"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="last_action",
            field=models.JSONField(
                blank=True,
                db_comment="Tuple: [timestamp, str].  The string values can be 'joined', 'logged in', 'called', 'played'",
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
            ),
        ),
    ]
