# Generated by Django 6.0.3 on 2026-03-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0100_alter_player_last_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournament",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
