# Generated by Django 6.0.3 on 2026-03-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0101_alter_tournament_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="explanation",
            field=models.CharField(
                blank=True,
                db_comment="Why the player made this call, e.g. from a bidding convention",
                default="",
                max_length=200,
            ),
        ),
    ]
