from typing import Any

from django.http import HttpRequest

class Table:
    request: HttpRequest
    class Meta: ...

    def __init__(self, data: Any = ..., **kwargs: Any) -> None: ...
    def paginate(self, **kwargs: Any) -> None: ...

def table_factory(model: type, **kwargs: Any) -> type[Table]: ...
