from typing import Any

from django.views.generic.list import ListView

class TableMixinBase:
    context_table_name: str
    table_pagination: dict[str, Any] | bool | None
    def get_context_table_name(self, table: Any) -> str: ...
    def get_table_pagination(self, table: Any) -> dict[str, Any] | bool: ...
    def get_paginate_by(self, table_data: Any) -> int | None: ...

class SingleTableMixin(TableMixinBase):
    table_class: type | None
    table_data: Any
    def get_table_class(self) -> type: ...
    def get_table(self, **kwargs: Any) -> Any: ...
    def get_table_data(self) -> Any: ...
    def get_table_kwargs(self) -> dict[str, Any]: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...

class SingleTableView(SingleTableMixin, ListView): ...

class MultiTableMixin(TableMixinBase):
    tables: list[Any] | None
    tables_data: list[Any] | None
    table_prefix: str
    def get_tables(self) -> list[Any]: ...
    def get_tables_data(self) -> list[Any] | None: ...
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]: ...
