* Oy
:PROPERTIES:
:UNNUMBERED: notoc
:END:
I've done this like six times, and I guess it's slowly getting better, but it's still not clean.

I need *one* bit of code that answers the question: can this Django user see this bit of this hand?  ~Board.can_see_cards_at~ is clearly an attempt to do that.

~_error_response_or_viewfunc~ and ~Board.relationship_to~ are sorta groping their way there.

I've considered using [[https://docs.djangoproject.com/en/5.1/topics/auth/default/#topic-authorization][django's built-in permissions]] to control access to hands, rather than doing it "by hand" (haw haw) as I'm currently doing; but it occurs to me that that stuff likely only controls access to model instances, whereas I need to control access to the individual seats (North, East, South, West) of a single board instance.

One example: in prod, if you're not logged in, <https://bridge.offby1.info/hand/55/> yells at you: ~Anonymous users like AnonymousUser can view only those boards that have been fully played~.  However, the associated tournament is complete, so it should let me see it.

I've already got this logic right somewhere else, but apparently whatever tries to render that page isn't using it.

Also there are a lot of functions and methods that seem redundant:

- ~views.hand._display_and_control~
- ~views.hand._error_response_or_viewfunc~
- ~models.board.Board.relationship_to~
- ~models.board.Board.can_see_cards_at~
- ~models.board.Board.what_can_they_see~
