# Generated by Django 5.0.1 on 2024-07-29 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='table',
            field=models.ForeignKey(blank=True, db_comment="If NULL, then I'm in the lobby", null=True, on_delete=django.db.models.deletion.CASCADE, to='bs_app.table'),
        ),
    ]
